// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © yuli-kamakura

//@version=6
indicator("Trade Value", overlay=true)

// Using ohlc4 (open+high+low+close)/4 for a more comprehensive average price calculation
// ohlc4 is a built-in variable that equals (open + high + low + close) / 4
tradeValue = volume * ohlc4

plot(
     tradeValue,
     title   = "Trade Value",
     format  = format.volume,
     color   = color.new(color.red, 100),  // 100% transparent
     style   = plot.style_line,
     linewidth = 1)
